name: Build LaTeX Document # A name for your workflow

on:
  push:
    branches: [ main ] # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: [ main ] # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    name: Build LaTeX
    runs-on: ubuntu-latest # The runner environment to execute the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3 # Use the GitHub Action for LaTeX
        with:
          root_file: main.tex # Replace with the path to your main .tex file
          args: -pdf # Optional arguments for latexmk (e.g., create a PDF)

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: latex-output
          path: output.pdf # Adjust the path based on your LaTeX output
